// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadiologiaAppNew.Data;

#nullable disable

namespace RadiologiaAppNew.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615141055_AddCollocazioneIdsToApparecchiatura")]
    partial class AddCollocazioneIdsToApparecchiatura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Ruoli", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RuoliClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UtentiClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UtentiLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UtentiRuoli", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UtentiToken", (string)null);
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Apparecchiatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbitoIntervento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caposala")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CorrenteMaxMa")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Costruttore")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAccettazione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCessazione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataRegistrazioneInail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataRegistrazioneStrims")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescrizioneZoneClassificate")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DipartimentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirettoreDipartimento")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirettoreDipartimentoEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirettoreDipartimentoEmailPec")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirettoreDipartimentoTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirettoreStruttura")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirettoreStrutturaEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirettoreStrutturaEmailPec")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirettoreStrutturaTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EdrEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EdrEmailPec")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EdrNome")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EdrTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAssistenza")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EnergiaMaxKev")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("GlobalService")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImmobileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InailRicevutaCessioneFile")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("InailRicevutaRegistrazioneFile")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("IntensitaCampoTesla")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("LanCollegata")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocaleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricola")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MedsquareInstallato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modello")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Modulo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoCessazione")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroAssistenza")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroPraticaInail")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PianoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PiantinaZoneClassificateFile")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrepostoEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrepostoEmailPec")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrepostoTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RepartoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RirEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RirEmailPec")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RirNome")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RirTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SapId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SfmEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SfmEmailPec")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SfmNome")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SfmTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiapDescrizione")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SitoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SocietaManutenzione")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatoInail")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatoStrims")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrimsIdApparecchiatura")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("StrimsNcCaricata")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StrimsNpCaricata")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrimsRicevutaCessioneFile")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrimsRicevutaRegistrazioneFile")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TecnicoRiferimento")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TensioneMaxKvolt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoMagnete")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipologia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.HasIndex("DipartimentoId");

                    b.HasIndex("LocaleId");

                    b.HasIndex("RepartoId");

                    b.ToTable("Apparecchiature");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuliAbilitati")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoInterno")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimoAccesso")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Utenti", (string)null);
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.CicloTrattamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AttivitaResiduaSiringaGbq")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("AttivitaSomministrataGbq")
                        .HasColumnType("decimal(6,3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSomministrazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffettiAvversi")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EsitoCiclo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FornitoreRadiofarmaco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("InfermiereSomministratore")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LottoRadiofarmaco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoModifica")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteCliniche")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroCiclo")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("OraSomministrazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PesoPazienteCicloKg")
                        .HasColumnType("decimal(5,1)");

                    b.HasKey("Id");

                    b.HasIndex("PazienteId");

                    b.ToTable("CicliTrattamento");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Collocazione.Immobile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SitoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SitoId");

                    b.ToTable("Immobili");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Edificio A — Diagnostica",
                            SitoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Edificio B — Terapia",
                            SitoId = 1
                        });
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Collocazione.Locale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codice")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("PianoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PianoId");

                    b.ToTable("Locali");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codice = "TAC-01",
                            Nome = "Sala TAC — 01",
                            PianoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Codice = "RX-02",
                            Nome = "Sala RX — 02",
                            PianoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Codice = "RM-10",
                            Nome = "Sala RM — 10",
                            PianoId = 2
                        },
                        new
                        {
                            Id = 4,
                            Codice = "PET-01",
                            Nome = "Sala PET-CT — 01",
                            PianoId = 3
                        });
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Collocazione.Piano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImmobileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImmobileId");

                    b.ToTable("Piani");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImmobileId = 1,
                            Nome = "Piano Terra",
                            Numero = 0
                        },
                        new
                        {
                            Id = 2,
                            ImmobileId = 1,
                            Nome = "Piano 1",
                            Numero = 1
                        },
                        new
                        {
                            Id = 3,
                            ImmobileId = 2,
                            Nome = "Piano Terra",
                            Numero = 0
                        });
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Collocazione.Reparto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsabile")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reparti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Radiologia",
                            Responsabile = "Dr. Rossi"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Medicina Nucleare",
                            Responsabile = "Dr. Bianchi"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Radioterapia",
                            Responsabile = "Dr. Verdi"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Risonanza Magnetica",
                            Responsabile = "Dr. Neri"
                        });
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Collocazione.Sito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Siti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Indirizzo = "Via della Salute, 1",
                            Nome = "Presidio Ospedaliero Principale"
                        });
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Costruttore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Paese")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SitoWeb")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Costruttori");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attivo = true,
                            Nome = "Siemens Healthineers",
                            Paese = "Germania"
                        },
                        new
                        {
                            Id = 2,
                            Attivo = true,
                            Nome = "GE HealthCare",
                            Paese = "USA"
                        },
                        new
                        {
                            Id = 3,
                            Attivo = true,
                            Nome = "Philips Healthcare",
                            Paese = "Paesi Bassi"
                        },
                        new
                        {
                            Id = 4,
                            Attivo = true,
                            Nome = "Canon Medical Systems",
                            Paese = "Giappone"
                        },
                        new
                        {
                            Id = 5,
                            Attivo = true,
                            Nome = "Hologic",
                            Paese = "USA"
                        },
                        new
                        {
                            Id = 6,
                            Attivo = true,
                            Nome = "Varex Imaging",
                            Paese = "USA"
                        });
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.DatoEmatologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CicloId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CreatininaMgDl")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("CromograninaA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DataPrelievo")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EgfrMlMin")
                        .HasColumnType("decimal(6,1)");

                    b.Property<decimal?>("HgbGdl")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NeutrofiliX10_9L")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PltX10_9L")
                        .HasColumnType("decimal(7,1)");

                    b.Property<decimal?>("PsaNgMl")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Timing")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TossicitaEmatologica")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WbcX10_9L")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("CicloId");

                    b.HasIndex("PazienteId");

                    b.ToTable("DatiEmatologici");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Dipartimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dipartimenti");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.FiguraResponsabile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApparecchiaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("GradoAbilitazione")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ruolo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidoAl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidoDal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApparecchiaturaId");

                    b.ToTable("FigureResponsabili");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.FileAllegato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApparecchiaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CicloId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DatoEmatologicoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("DimensioneBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeOriginale")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeStorage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NotificaPraticaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NullaOstaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PazienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SostituisceFileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VerbaleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VerificaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Versione")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApparecchiaturaId");

                    b.HasIndex("CicloId");

                    b.HasIndex("DatoEmatologicoId");

                    b.HasIndex("NotificaPraticaId");

                    b.HasIndex("NullaOstaId");

                    b.HasIndex("PazienteId");

                    b.HasIndex("VerbaleId");

                    b.HasIndex("VerificaId");

                    b.ToTable("FileAllegati");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.ModelloApparecchiatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostrutoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipologia")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CostrutoreId");

                    b.ToTable("ModelliApparecchiatura");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.NotificaPratica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApparecchiaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInvioRspp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNotifica")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnteDestinatario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("InviatoRspp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroProtocolloPec")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApparecchiaturaId");

                    b.ToTable("NotifichePratica");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.NullaOsta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApparecchiaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRilascio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnteRilascio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApparecchiaturaId");

                    b.ToTable("NullaOsta");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.PazienteLu177", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AltezzaCm")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal?>("AttivitaPerCicloGbq")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodicePaziente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Controindicazioni")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInizioTrattamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPrimaVisita")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosiPrincipale")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EgfrMlMin")
                        .HasColumnType("decimal(6,1)");

                    b.Property<string>("FunzionalitaEpatica")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Indicazione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("IntervallSettimane")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicoInviante")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NCicliPianificati")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroNosologico")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("decimal(5,1)");

                    b.Property<string>("ProtocolloTerapeutico")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepartoInviante")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sesso")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatoPaziente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodicePaziente")
                        .IsUnique();

                    b.ToTable("PazientiLu177");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.ProtocolloVerifica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmbitiApplicabilita")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEntrataVigore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PeriodicitaMesi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Revisione")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipologieApplicabilita")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProtocolliVerifica");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmbitiApplicabilita = "Radiologia",
                            Attivo = true,
                            Codice = "PA-RAD-001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEntrataVigore = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descrizione = "Protocollo Accettazione — Radiologia Diagnostica",
                            Revisione = "Rev. 1",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 2,
                            AmbitiApplicabilita = "Radiologia",
                            Attivo = true,
                            Codice = "PP-RAD-001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEntrataVigore = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descrizione = "Protocollo Periodico Annuale — Radiologia Diagnostica",
                            PeriodicitaMesi = 12,
                            Revisione = "Rev. 1",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 3,
                            AmbitiApplicabilita = "Radiologia",
                            Attivo = true,
                            Codice = "PA-TAC-001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEntrataVigore = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descrizione = "Protocollo Accettazione — TAC",
                            Revisione = "Rev. 1",
                            Tipo = 0,
                            TipologieApplicabilita = "TAC"
                        },
                        new
                        {
                            Id = 4,
                            AmbitiApplicabilita = "RM",
                            Attivo = true,
                            Codice = "PP-RM-001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEntrataVigore = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descrizione = "Protocollo Periodico Semestrale — Risonanza Magnetica",
                            PeriodicitaMesi = 6,
                            Revisione = "Rev. 1",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 5,
                            AmbitiApplicabilita = "Radiologia,RadiologiaInterventistica",
                            Attivo = true,
                            Codice = "PV-EDR-001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEntrataVigore = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descrizione = "Prima Verifica EDR — Radiologia",
                            Revisione = "Rev. 1",
                            Tipo = 4
                        },
                        new
                        {
                            Id = 6,
                            AmbitiApplicabilita = "Radiologia",
                            Attivo = true,
                            Codice = "LDR-RAD-001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEntrataVigore = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descrizione = "Verifica LDR Annuale — Radiologia",
                            PeriodicitaMesi = 12,
                            Revisione = "Rev. 1",
                            Tipo = 3
                        });
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.RecordVerifica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Anno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApparecchiaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BenestareCliniciData")
                        .HasColumnType("TEXT");

                    b.Property<string>("BenestareClinicoBy")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("BenestareQualitaTecnicaBy")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BenestareQualitaTecnicaData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInterventoManutenzione")
                        .HasColumnType("TEXT");

                    b.Property<int>("Esito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoGuasto")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProssimaVerificaData")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtocolloId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Semestre")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SocietaManutenzione")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TecnicoManutentore")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoGuasto")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoInterventoManutenzione")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApparecchiaturaId");

                    b.HasIndex("ProtocolloId");

                    b.ToTable("RecordVerifiche");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.SocietaManutenzione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAssistenza")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalService")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroAssistenza")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroReperibilita")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SitoWeb")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SocietaManutenzione");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Verbale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApparecchiaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AzioniCorrettive")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ClassificazioneConsolle")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ClassificazioneSalaDiagnostica")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ClassificazioneSalaPreparazione")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CorrettezzaDosimetroAmbientale")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataChiusura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSopralluogo")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FunzionamentoSegnaleticaLuminosaConsolle")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FunzionamentoSegnaleticaLuminosaDiagnostica")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FunzionamentoSegnaleticaLuminosaPreparazione")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("InterLockConsolle")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("InterLockPreparazione")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NonConformita")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Oggetto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Partecipanti")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Piantina")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("PresenzaDosimetroAmbientale")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("PresenzaNormePortatili")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("PresenzaNormeRadioprotezione")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rilievi")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScadenzaAzioni")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SegnaleticaConsolle")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SegnaleticaGravidanzaConsolle")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SegnaleticaGravidanzaDiagnostica")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SegnaleticaGravidanzaPreparazione")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SegnaleticaRischioGravidanza")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SegnaleticaRischioRadiazioni")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SegnaleticaSalaDiagnostica")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SegnaleticaSalaPreparazione")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApparecchiaturaId");

                    b.ToTable("Verbali");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadiologiaAppNew.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Apparecchiatura", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.Dipartimento", "Dipartimento")
                        .WithMany("Apparecchiature")
                        .HasForeignKey("DipartimentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RadiologiaAppNew.Models.Collocazione.Locale", "Locale")
                        .WithMany("Apparecchiature")
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RadiologiaAppNew.Models.Collocazione.Reparto", "Reparto")
                        .WithMany("Apparecchiature")
                        .HasForeignKey("RepartoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dipartimento");

                    b.Navigation("Locale");

                    b.Navigation("Reparto");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.CicloTrattamento", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.PazienteLu177", "Paziente")
                        .WithMany("CicliTrattamento")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paziente");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Collocazione.Immobile", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.Collocazione.Sito", "Sito")
                        .WithMany("Immobili")
                        .HasForeignKey("SitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sito");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Collocazione.Locale", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.Collocazione.Piano", "Piano")
                        .WithMany("Locali")
                        .HasForeignKey("PianoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piano");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Collocazione.Piano", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.Collocazione.Immobile", "Immobile")
                        .WithMany("Piani")
                        .HasForeignKey("ImmobileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Immobile");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.DatoEmatologico", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.CicloTrattamento", "Ciclo")
                        .WithMany("DatiEmatologici")
                        .HasForeignKey("CicloId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RadiologiaAppNew.Models.PazienteLu177", "Paziente")
                        .WithMany("DatiEmatologici")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciclo");

                    b.Navigation("Paziente");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.FiguraResponsabile", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.Apparecchiatura", "Apparecchiatura")
                        .WithMany("FigureResponsabili")
                        .HasForeignKey("ApparecchiaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apparecchiatura");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.FileAllegato", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.Apparecchiatura", "Apparecchiatura")
                        .WithMany("FileAllegati")
                        .HasForeignKey("ApparecchiaturaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RadiologiaAppNew.Models.CicloTrattamento", "Ciclo")
                        .WithMany("FileAllegati")
                        .HasForeignKey("CicloId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RadiologiaAppNew.Models.DatoEmatologico", null)
                        .WithMany("FileAllegati")
                        .HasForeignKey("DatoEmatologicoId");

                    b.HasOne("RadiologiaAppNew.Models.NotificaPratica", null)
                        .WithMany("FileAllegati")
                        .HasForeignKey("NotificaPraticaId");

                    b.HasOne("RadiologiaAppNew.Models.NullaOsta", null)
                        .WithMany("FileAllegati")
                        .HasForeignKey("NullaOstaId");

                    b.HasOne("RadiologiaAppNew.Models.PazienteLu177", "Paziente")
                        .WithMany("FileAllegati")
                        .HasForeignKey("PazienteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RadiologiaAppNew.Models.Verbale", "Verbale")
                        .WithMany("FileAllegati")
                        .HasForeignKey("VerbaleId");

                    b.HasOne("RadiologiaAppNew.Models.RecordVerifica", "Verifica")
                        .WithMany("FileAllegati")
                        .HasForeignKey("VerificaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Apparecchiatura");

                    b.Navigation("Ciclo");

                    b.Navigation("Paziente");

                    b.Navigation("Verbale");

                    b.Navigation("Verifica");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.ModelloApparecchiatura", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.Costruttore", "Costruttore")
                        .WithMany("Modelli")
                        .HasForeignKey("CostrutoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Costruttore");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.NotificaPratica", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.Apparecchiatura", "Apparecchiatura")
                        .WithMany("NotifichePratica")
                        .HasForeignKey("ApparecchiaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apparecchiatura");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.NullaOsta", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.Apparecchiatura", "Apparecchiatura")
                        .WithMany("NullaOsta")
                        .HasForeignKey("ApparecchiaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apparecchiatura");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.RecordVerifica", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.Apparecchiatura", "Apparecchiatura")
                        .WithMany("RecordVerifiche")
                        .HasForeignKey("ApparecchiaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadiologiaAppNew.Models.ProtocolloVerifica", "Protocollo")
                        .WithMany("RecordVerifiche")
                        .HasForeignKey("ProtocolloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apparecchiatura");

                    b.Navigation("Protocollo");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Verbale", b =>
                {
                    b.HasOne("RadiologiaAppNew.Models.Apparecchiatura", "Apparecchiatura")
                        .WithMany("Verbali")
                        .HasForeignKey("ApparecchiaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apparecchiatura");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Apparecchiatura", b =>
                {
                    b.Navigation("FigureResponsabili");

                    b.Navigation("FileAllegati");

                    b.Navigation("NotifichePratica");

                    b.Navigation("NullaOsta");

                    b.Navigation("RecordVerifiche");

                    b.Navigation("Verbali");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.CicloTrattamento", b =>
                {
                    b.Navigation("DatiEmatologici");

                    b.Navigation("FileAllegati");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Collocazione.Immobile", b =>
                {
                    b.Navigation("Piani");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Collocazione.Locale", b =>
                {
                    b.Navigation("Apparecchiature");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Collocazione.Piano", b =>
                {
                    b.Navigation("Locali");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Collocazione.Reparto", b =>
                {
                    b.Navigation("Apparecchiature");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Collocazione.Sito", b =>
                {
                    b.Navigation("Immobili");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Costruttore", b =>
                {
                    b.Navigation("Modelli");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.DatoEmatologico", b =>
                {
                    b.Navigation("FileAllegati");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Dipartimento", b =>
                {
                    b.Navigation("Apparecchiature");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.NotificaPratica", b =>
                {
                    b.Navigation("FileAllegati");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.NullaOsta", b =>
                {
                    b.Navigation("FileAllegati");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.PazienteLu177", b =>
                {
                    b.Navigation("CicliTrattamento");

                    b.Navigation("DatiEmatologici");

                    b.Navigation("FileAllegati");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.ProtocolloVerifica", b =>
                {
                    b.Navigation("RecordVerifiche");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.RecordVerifica", b =>
                {
                    b.Navigation("FileAllegati");
                });

            modelBuilder.Entity("RadiologiaAppNew.Models.Verbale", b =>
                {
                    b.Navigation("FileAllegati");
                });
#pragma warning restore 612, 618
        }
    }
}
